version: "3.9"
services:
    message_queue:
        image: rabbitmq:3-management
        # container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
        healthcheck:
            test: rabbitmq-diagnostics -q check_running
            interval: 30s
            timeout: 30s
            retries: 5
    data_extractor:
        build:
            context: ./data_extractor
            dockerfile: Dockerfile
        environment:
            RABBIT_MQ_HOST: message_queue
            RABBIT_MQ_PORT: 5672
            RABBIT_MQ_USER: user
            RABBIT_MQ_PASS: pass
        depends_on:
            message_queue:
                condition: service_healthy
    data_persister:
        build:
            content: ./posts_persister
            dockerfile: Dockerfile
        environment:
            RABBIT_MQ_HOST: message_queue
            RABBIT_MQ_PORT: 5672
            RABBIT_MQ_USER: user
            RABBIT_MQ_PASS: pass
        depends_on:
            message_queue:
                condition: service_healthy
