version: "3.4"
services:
    data_extractor:
        build:
            context: ./data_extractor
            dockerfile: Dockerfile
        environment:
            RABBIT_MQ_HOST: message_queue
            RABBIT_MQ_PORT: 5672
        depends_on:
            - message_queue
    message_queue:
        image: rabbitmq:3-management
        restart: always
        ports:
            - 5672:5672
            - 8080:15672
        environment:
            - POSTGRES_DB=tasks_tracker
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password
